[package]
name = "soroban-ledger-snapshot-example"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "21.4.0" }

[dev-dependencies]
soroban-sdk = { version = "21.4.0", features = ["testutils"] }
